#!/usr/bin/env bash
# Bash script that shows information about the given subdomain

show_information () {

     info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | tr '\t' ' ' | cut -d" " -f5 )
     echo "$2 $info" | awk '{print "The subdomain " $1 " is a A record and points to " $2}'

}

if [ "$#" == 1 ]
then
    show_information "$1" "www"
    show_information "$1" "lb-01"
    show_information "$1" "web-01"
    show_information "$1" "web-02"
else
    show_information "$1" "$2"
fi
