#!/usr/bin/env bash
# Bash script that configures a nginx web server.

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Adjusting the Firewall
sudo ufw allow 'Nginx HTTP'

# Changing permissions to create a new html file
sudo chown -R $USER:$USER /var/www/html
sudo chown -R $USER:$USER /usr/share/nginx/html

# Creating a new html file
echo "Holberton School for the win!" > /var/www/html/index.html

# Redirecting so that /redirect_me is redirecting to another page.
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# creating custom 404 eror page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Configure your Nginx server to have a custom 404 page.
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
# Starting the server
sudo service nginx reload
sudo service nginx start
