#!/usr/bin/env bash                                                                                                                            # Bash script that configures a nginx web server.

# Installing nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Adjusting the Firewall
sudo ufw allow 'Nginx HTTP'

# Changing permissions to create a new html file
sudo chown -R $USER:$USER /var/www/html

# Creating a new html file
echo "Holberton School for the win!" > /var/www/html/index.html

# Adding a new HTTP response custom header
sudo sed -i '/listen 80 default_server/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Starting the server
sudo service nginx start
