#!/usr/bin/env bash
# Bash script that configure HAproxy on your Ubuntu 16.04 server.

# Install some updates
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Append the settings to the haproxy.cfg file

# SETTINGS THAT WILL NEED
# frontend http_front
# 	bind *:80
# 	stats uri /haproxy?stats
# 	default_backend http_back

# backend http_back
# 	balance roundrobin
# 	server 1569-web-01 34.75.190.131:80 check
#	server 1569-web-02 104.196.128.209:80 check

printf "frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
printf "backend http_back\n\tbalance roundrobin\n\tserver 1569-web-01 34.75.190.131:80 check\n\tserver 1569-web-02 104.196.128.209:80 check\n" >> /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo systemctl restart haproxy
