#!/usr/bin/env bash
# Bash script that configure HAproxy on your Ubuntu 16.04 server.

# Install some updates
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Append the settings to the haproxy.cfg file

# SETTINGS THAT WILL NEED
# listen http-in
# 	bind *:80
# 	mode http
# 	balance roundrobin
# 	server 1569-web-01 34.75.190.131:80
# 	server 1569-web-02 104.196.128.209:80


printf "\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1569-web-01 34.75.190.131:80\n\tserver 1569-web-02 104.196.128.209:80\n\t\n" >> /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo systemctl restart haproxy
