#!/usr/bin/env bash
# Bash script that configure HAproxy on your Ubuntu 16.04 server.

# Install some updates
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Enable haproxy to start at boot
printf "ENABLED=1" >> /etc/default/haproxy

# Append the settings to the haproxy.cfg file

# SETTINGS THAT WILL NEED
# frontend http_front
# 	bind *:80
# 	mode http
# 	default_backend web_back

# backend web_back
# 	balance roundrobin
# 	server 1569-web-01 34.75.190.131:80 check
#	server 1569-web-02 104.196.128.209:80 check

printf "frontend web_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_back\n" >> /etc/haproxy/haproxy.cfg
printf "backend web_back\n\tbalance roundrobin\n\tserver 1569-web-01 34.75.190.131:80 check\n\tserver 1569-web-02 104.196.128.209:80 check\n" >> /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
