#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Generating a MySQL dump
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compressing the file into a .tar.gz file
tar -zcvf "$(date '+%m-%d-%Y').tar.gz" backup.sql
